source:
  config:
    api_key: 53ebf3635b48448ce7d0a462af61bcc3
    country: in
    from_date: '2025-10-01'
    lang: en
    max: 60
    query: Stocks OR Finance
    sortby: publishedAt
    to_date: '2025-10-31'
  docker_image: airbyte/source-gnews:0.2.23
