kafka:
  brokers:
    - redpanda-0:9092
  sasl:
    enabled: true
    username: superuser
    password: secretpassword
    mechanism: SCRAM-SHA-256

schemaRegistry:
  enabled: true
  urls:
    - http://redpanda-0:8081

redpanda:
  adminApi:
    enabled: true
    urls:
      - http://redpanda-0:9644