FROM python:3.13-slim
ARG PIPELINE
ENV PIPELINE=${PIPELINE}
WORKDIR /app
RUN pip install --no-cache-dir uv
COPY requirements.txt .
RUN uv pip install --system -r requirements.txt
COPY src/ src/
COPY config/ config/
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app
CMD ["python", "src/layers/silver_layer/pipeline.py"]